# docker-compose.yml
version: "3"
services:
  app-test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgres://${PG_SQL_USERNAME}:${PG_SQL_PASSWORD}@postgres-test:5432/${PG_SQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_PASSWORD: ${GITHUB_PASSWORD}
      PASSWORD_SALT: ${PASSWORD_SALT}
      NODE_PORT: 3000
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres-test:
    image: postgres:10.4
    ports:
      - "${PG_SQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_SQL_USERNAME}
      POSTGRES_PASSWORD: ${PG_SQL_PASSWORD}
      POSTGRES_DB: ${PG_SQL_DATABASE}
