# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${PG_SQL_USERNAME}:${PG_SQL_PASSWORD}@postgres:5432/${PG_SQL_DATABASE}
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
    ports:
      - "${SERVER_PORT}:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "${PG_SQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${PG_SQL_USERNAME}
      POSTGRES_PASSWORD: ${PG_SQL_PASSWORD}
      POSTGRES_DB: ${PG_SQL_DATABASE}
